### ISSUE TITLE
When creating Plotly heatmaps Legend Disappears

### ISSUE THREAD

**Issue by Rohit-Satyam** [smped/ngsReports#38]
I realized that when I use `usePlotly = T`, the legend from the heatmaps disappears. This behaviour is repetitive with all the graphs. Can this be fixed??

Also, I tried using `subplot` to club the graphs and weird legends appear.  

![image](https://user-images.githubusercontent.com/55479480/220361587-bd710ba2-3f84-43a1-a1d8-0cde34cac870.png)

```r
c <- plotSeqContent(fdl,usePlotly = T)
d <- plotSeqQuals(fdl,usePlotly = T)
plotly::subplot(c,d,shareY = TRUE) %>% layout(showlegend = T)
```
Can this be fixed too?
![image](https://user-images.githubusercontent.com/55479480/220362453-c04aeb4f-a4f6-401f-8430-c21c99a49829.png)

**Comment by smped** [comment]
Hi @Rohit-Satyam ,
Thanks for asking & that's a good question. We find some legends quite difficult to work with when using plotly, exactly as you've noticed. Leaving them off was an intentional design decision for this reason. Also, the hover function does enable you to get the actual values from any relevant section of the plot anyway, somewhat negating the need for a legend when running interactively.
